"""Models for the monthly compilation video generator.

Defines segments extracted from top-performing videos, the compilation
script structure, and the final assembly result.
"""

from __future__ import annotations

import uuid
from datetime import date, datetime
from decimal import Decimal

from pydantic import BaseModel, Field

# ---------------------------------------------------------------------------
# Peak segment — a high-retention clip extracted from an existing video
# ---------------------------------------------------------------------------


class PeakSegment(BaseModel):
    """A high-engagement segment identified from audience retention data.

    The engagement score combines relative retention (above video average)
    with absolute view count so that a 90% retention spike on a 500K-view
    video outranks a 95% spike on a 2K-view video.
    """

    video_id: uuid.UUID
    video_title: str
    youtube_video_id: str = Field(description="Needed to download the source video")
    start_seconds: float = Field(ge=0)
    end_seconds: float = Field(gt=0)
    duration_seconds: float = Field(gt=0)
    retention_percent: float = Field(
        ge=0, le=100, description="Avg retention % during this segment"
    )
    view_count: int = Field(ge=0, description="Total video views at time of analysis")
    engagement_score: float = Field(
        ge=0,
        description="retention_above_avg * sqrt(views) — used for ranking",
    )
    scene_description: str = Field(
        default="", description="Brief description of what happens in this segment"
    )


class SegmentTransition(BaseModel):
    """Narration bridging two consecutive peak segments."""

    from_segment_index: int = Field(ge=0)
    to_segment_index: int = Field(ge=0)
    narration_text: str
    estimated_duration_seconds: float = Field(gt=0)


# ---------------------------------------------------------------------------
# Compilation script — new narration generated by Claude
# ---------------------------------------------------------------------------


class CompilationScript(BaseModel):
    """New narration tying together the best segments into a cohesive video.

    YouTube's reused-content policy requires substantial original commentary,
    so we generate a full intro, outro, and bridging narration between every
    segment (typically 40-60 seconds of new voiceover per transition).
    """

    intro_narration: str = Field(
        description="60-90 second original intro framing the compilation theme"
    )
    outro_narration: str = Field(description="30-60 second outro with CTA and next-video tease")
    transitions: list[SegmentTransition] = Field(
        description="Narration bridges between consecutive segments"
    )
    total_new_narration_words: int = Field(ge=0)
    estimated_new_narration_seconds: float = Field(gt=0)
    month_label: str = Field(description="e.g. 'January 2026'")
    theme: str = Field(
        default="best_of",
        description="Compilation theme: best_of, most_shocking, unsolved, etc.",
    )
    cost: Decimal = Field(
        default=Decimal("0"),
        ge=0,
        description="Claude API cost for script generation",
    )


# ---------------------------------------------------------------------------
# Compilation result — the final assembled video
# ---------------------------------------------------------------------------


class CompilationResult(BaseModel):
    """Final output of the monthly compilation pipeline."""

    video_id: uuid.UUID = Field(description="New video record created for the compilation")
    channel_id: uuid.UUID
    title: str
    description: str
    month: date
    segments_used: int = Field(ge=1)
    total_duration_seconds: float = Field(gt=0)
    new_narration_seconds: float = Field(gt=0)
    original_content_ratio: float = Field(
        ge=0,
        le=1,
        description="Fraction of runtime that is new narration (target: >= 0.30)",
    )
    file_path: str = Field(description="R2 object key for the final MP4")
    file_url: str = Field(description="Public or signed URL")
    file_size_bytes: int = Field(ge=0)
    total_cost_usd: Decimal = Field(ge=0)
    segment_details: list[PeakSegment] = Field(description="The segments that made the cut")
    created_at: datetime = Field(default_factory=datetime.utcnow)


# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------


class CompilationConfig(BaseModel):
    """Tunable parameters for the compilation generator."""

    min_segments: int = Field(default=5, ge=3, description="Min segments to include")
    max_segments: int = Field(default=12, ge=5, description="Max segments to include")
    min_segment_seconds: float = Field(default=30.0, gt=10, description="Shortest clip to extract")
    max_segment_seconds: float = Field(default=180.0, le=300, description="Longest clip to extract")
    target_duration_minutes: int = Field(
        default=20, ge=10, le=45, description="Target compilation length"
    )
    min_original_content_ratio: float = Field(
        default=0.30,
        ge=0.20,
        le=0.50,
        description="Min fraction of new narration to avoid reused-content flag",
    )
    retention_lookback_days: int = Field(
        default=90,
        ge=30,
        description="Only consider videos published within this window",
    )
    min_video_views: int = Field(
        default=1000,
        ge=0,
        description="Skip videos below this view threshold",
    )
    crossfade_seconds: float = Field(
        default=1.0, ge=0.5, le=3.0, description="Audio/video crossfade between segments"
    )
