"""Models for the series planner — multi-episode narrative arcs."""

from __future__ import annotations

import uuid
from datetime import datetime
from decimal import Decimal
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field

from src.models.script import APICallCost

# ---------------------------------------------------------------------------
# Type aliases
# ---------------------------------------------------------------------------

SeriesType = Literal["multi_part", "thematic_season", "ongoing_arc"]
SeriesStatus = Literal["planning", "in_production", "active", "completed"]
EpisodeStatus = Literal["planned", "scripted", "produced", "published"]

# ---------------------------------------------------------------------------
# Inputs
# ---------------------------------------------------------------------------


class SeriesInput(BaseModel):
    """User-facing input for creating a new series."""

    title: str = Field(min_length=3, max_length=300)
    description: str = Field(default="", max_length=5000)
    channel_id: uuid.UUID
    series_type: SeriesType = "multi_part"
    planned_episodes: int = Field(default=3, ge=1, le=52)
    case_name: str | None = Field(default=None, description="For multi_part: single case name")
    theme: str | None = Field(default=None, description="For thematic_season: category theme")
    topic_ids: list[uuid.UUID] | None = Field(
        default=None, description="Pre-assigned topic IDs per episode"
    )


# ---------------------------------------------------------------------------
# Episode arc planning
# ---------------------------------------------------------------------------


class EpisodeArcPlan(BaseModel):
    """Claude-generated plan for a single episode within the arc."""

    episode_number: int = Field(ge=1)
    title: str
    core_question: str = Field(description="Central question this episode answers")
    key_revelation: str = Field(description="The main reveal / twist")
    open_loop_forward: str = Field(
        description="Unanswered question that carries into the next episode"
    )
    suggested_hook_type: str = Field(
        default="cold_open",
        description="Recommended hook type from the 5 rotation options",
    )
    estimated_length_minutes: int = Field(default=15, ge=5, le=30)


class SeriesArc(BaseModel):
    """Complete narrative arc for a series, generated by Claude."""

    series_id: uuid.UUID
    overarching_thesis: str = Field(description="The single big question the series answers")
    narrative_structure: str = Field(
        description="e.g. 'linear chronological', 'investigation spiral'"
    )
    episodes: list[EpisodeArcPlan]
    recurring_motifs: list[str] = Field(
        default_factory=list,
        description="Visual/thematic elements that recur across episodes",
    )
    cliffhanger_strategy: str = Field(
        default="",
        description="How episodes end to drive next-episode consumption",
    )
    cost: APICallCost


# ---------------------------------------------------------------------------
# Cross-video hooks
# ---------------------------------------------------------------------------


class CrossLink(BaseModel):
    """A suggested info-card linking to another episode."""

    target_episode_number: int = Field(ge=1)
    reason: str = Field(description="Why this link is relevant at this moment")
    suggested_timestamp_description: str = Field(
        description="When in the episode to show this card"
    )


class CrossVideoHooks(BaseModel):
    """Generated hooks that tie one episode to the rest of the series."""

    series_id: uuid.UUID
    episode_number: int = Field(ge=1)
    recap_narration: str = Field(description="15-30s recap of previous episodes")
    teaser_narration: str = Field(description="10-20s teaser for next episode")
    end_screen_cta: str = Field(description="Text for end screen card")
    description_cross_links: str = Field(
        default="",
        description="Formatted description block with series links",
    )
    cross_links: list[CrossLink] = Field(default_factory=list)
    cost: APICallCost


# ---------------------------------------------------------------------------
# Analytics
# ---------------------------------------------------------------------------


class EpisodeMetric(BaseModel):
    """Per-episode analytics within a series."""

    episode_number: int
    video_id: uuid.UUID | None = None
    title: str = ""
    views: int = 0
    watch_minutes: Decimal = Decimal("0")
    avg_view_duration_seconds: Decimal = Decimal("0")
    ctr: Decimal = Decimal("0")
    revenue: Decimal = Decimal("0")


class SeriesAnalytics(BaseModel):
    """Aggregated analytics across all episodes of a series."""

    series_id: uuid.UUID
    series_title: str = ""
    total_episodes: int = 0
    published_episodes: int = 0
    total_views: int = 0
    total_watch_minutes: Decimal = Decimal("0")
    avg_view_duration_seconds: Decimal = Decimal("0")
    avg_ctr: Decimal = Decimal("0")
    total_subscribers_gained: int = 0
    total_revenue: Decimal = Decimal("0")
    episode_metrics: list[EpisodeMetric] = Field(default_factory=list)
    episode_completion_rates: dict[int, float] = Field(
        default_factory=dict,
        description="episode_number → % who watched next episode",
    )
    avg_session_depth: float = Field(
        default=0.0,
        description="Average videos watched per session within series",
    )
    series_vs_standalone_multiplier: float = Field(
        default=1.0,
        description="View multiplier vs standalone videos on same channel",
    )
    best_performing_episode: int | None = None
    drop_off_episode: int | None = None


# ---------------------------------------------------------------------------
# Series suggestions
# ---------------------------------------------------------------------------


class SeriesSuggestion(BaseModel):
    """AI-generated suggestion for a new series."""

    title: str
    description: str
    series_type: SeriesType
    suggested_episodes: int = Field(ge=2, le=12)
    rationale: str = Field(description="Why this series would perform well")
    estimated_total_views: int = Field(ge=0)
    source_topic_ids: list[uuid.UUID] = Field(default_factory=list)
    confidence_score: float = Field(ge=0.0, le=1.0, default=0.5)


class SeriesSuggestionResult(BaseModel):
    """Wrapper pairing suggestions with cost."""

    suggestions: list[SeriesSuggestion]
    cost: APICallCost


# ---------------------------------------------------------------------------
# DB response models
# ---------------------------------------------------------------------------


class SeriesResponse(BaseModel):
    """Database row for a series."""

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "id": "a7b8c9d0-e1f2-3456-0123-567890123456",
                "title": "The Wirecard Files",
                "description": "A 4-part deep-dive into Europe's biggest fintech fraud.",
                "channel_id": "11111111-2222-3333-4444-555555555555",
                "series_type": "multi_part",
                "planned_episodes": 4,
                "youtube_playlist_id": None,
                "arc_plan": None,
                "status": "in_production",
                "created_at": "2026-03-01T10:00:00Z",
                "updated_at": "2026-03-15T14:00:00Z",
            }
        }
    )

    id: uuid.UUID
    title: str
    description: str
    channel_id: uuid.UUID
    series_type: str
    planned_episodes: int
    youtube_playlist_id: str | None = None
    arc_plan: dict[str, Any] | None = None
    status: str
    created_at: datetime
    updated_at: datetime

    @classmethod
    def from_row(cls, row: dict[str, object]) -> SeriesResponse:
        return cls.model_validate(row)


class SeriesEpisodeResponse(BaseModel):
    """Database row for a series episode."""

    id: uuid.UUID
    series_id: uuid.UUID
    episode_number: int
    video_id: uuid.UUID | None = None
    title: str
    core_question: str
    key_revelation: str
    open_loop_forward: str
    recap_narration: str
    teaser_narration: str
    end_screen_cta: str
    cross_links: list[dict[str, Any]] | None = None
    status: str
    created_at: datetime
    updated_at: datetime

    @classmethod
    def from_row(cls, row: dict[str, object]) -> SeriesEpisodeResponse:
        return cls.model_validate(row)


class SeriesWithEpisodes(BaseModel):
    """Series record with all its episodes."""

    series: SeriesResponse
    episodes: list[SeriesEpisodeResponse]
