-- CrimeMill Initial Schema
-- This migration will be fully generated by Batch 1, Prompt P1.
-- Run via Supabase SQL Editor or `supabase db push`.
--
-- This file provides the core tables needed for the pipeline to function.
-- Additional tables (scripts, voiceovers, images, etc.) will be added
-- in subsequent migration files.

-- Enable required extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Channels table
CREATE TABLE IF NOT EXISTS channels (
    id          UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name        TEXT NOT NULL,
    youtube_channel_id TEXT NOT NULL DEFAULT '',
    description TEXT NOT NULL DEFAULT '',
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Videos table
CREATE TABLE IF NOT EXISTS videos (
    id            UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    channel_id    UUID NOT NULL REFERENCES channels(id),
    title         TEXT NOT NULL,
    topic         TEXT NOT NULL,
    status        TEXT NOT NULL DEFAULT 'pending'
                  CHECK (status IN (
                      'pending', 'topic_selected', 'script_generated',
                      'media_generating', 'media_complete', 'assembling',
                      'assembled', 'uploading', 'published', 'failed', 'cancelled'
                  )),
    error_message TEXT,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_videos_channel_id ON videos(channel_id);
CREATE INDEX IF NOT EXISTS idx_videos_status ON videos(status);

-- Pipeline jobs (Postgres-based job queue)
CREATE TABLE IF NOT EXISTS pipeline_jobs (
    id            UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    video_id      UUID NOT NULL REFERENCES videos(id),
    stage         TEXT NOT NULL,
    status        TEXT NOT NULL DEFAULT 'pending'
                  CHECK (status IN ('pending', 'running', 'completed', 'dead_letter', 'cancelled')),
    priority      INT NOT NULL DEFAULT 0,
    payload       JSONB NOT NULL DEFAULT '{}',
    result        JSONB,
    retry_count   INT NOT NULL DEFAULT 0,
    max_retries   INT NOT NULL DEFAULT 3,
    error_message TEXT,
    visible_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    started_at    TIMESTAMPTZ,
    completed_at  TIMESTAMPTZ,
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_pipeline_jobs_video_id ON pipeline_jobs(video_id);
CREATE INDEX IF NOT EXISTS idx_pipeline_jobs_status_visible ON pipeline_jobs(status, visible_at)
    WHERE status = 'pending';

-- Generation costs for tracking API spend
CREATE TABLE IF NOT EXISTS generation_costs (
    id           UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    video_id     UUID NOT NULL REFERENCES videos(id),
    stage        TEXT NOT NULL,
    provider     TEXT NOT NULL,
    model        TEXT NOT NULL,
    input_units  INT NOT NULL DEFAULT 0,
    output_units INT NOT NULL DEFAULT 0,
    cost_usd     NUMERIC(10, 6) NOT NULL DEFAULT 0,
    latency_ms   INT NOT NULL DEFAULT 0,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_generation_costs_video_id ON generation_costs(video_id);
